import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Sidebar from "@/components/ui/Sidebar"
import Navbar from "@/components/ui/Navbar"
import { auth } from "@/auth"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Surf data App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()

  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ height: "calc(100vh - 90px)", overflowY: "auto" }}
      >
        {session ? (
          <>
            <Navbar />

            <Sidebar>
              <main className="w-100 h-full p-3">{children}</main>
            </Sidebar>
          </>
        ) : (
          <>{children}</>
        )}
      </body>
    </html>
  )
}
