import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Head from "next/head"
import Sidebar from "@/components/Sidebar"
import Navbar from "@/components/Navbar"
import { options } from "./api/auth/[...nextauth]/options"
import { getServerSession } from "next-auth"
import { redirect } from "next/navigation"
import AuthProvider from "./context/AuthProvider" // gives access to session data to client side pages
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Surf data App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(options)

  // if (!session) {
  //   redirect("api/auth/signin?callbackUrl=/server")
  // }

  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;600;700&display=swap"
        />
      </Head>
      <body
        className={inter.className + "flex flex-row"}
        style={{ height: "calc(100vh - 90px)", overflowY: "auto" }}
      >
        <AuthProvider>
          <Navbar />
          <Sidebar>{children}</Sidebar>
        </AuthProvider>

        {/* {session ? (
          <div>
            <Navbar />
            <Sidebar>{children}</Sidebar>
          </div>
        ) : (
          <div>{children}</div>
        )} */}
      </body>
    </html>
  )
}
